### ISSUE TITLE
Exposed function names too generic ...

### ISSUE THREAD

**Issue by nkolban** [ibm-watson-iot/iot-embeddedc#1]
Looking at the list of exposed names from the library, we see that some of them are:
- setCommandHandler
- publishEvent
- disconnect
- initialize
- isConnected
- yield

The names of these C functions don't qualify them as being part of the iotf-embeddedc library.  What this means to me is that iotf-embeddedc is being too "presumptious" in its importance.  For it to claim the right to use methods named "initialize", "disconnect" and "yield" precludes these from being exposed by other (also presumptious) libraries or user code.

This issue suggests the examination of the library to see if the functions might not be better exposed in a qualified manner such as either:
1. Prefixing them.   For example iotf_yield(), iotf_disconnect(), iotf_initialize()
2. Indirecting them.   Fore example, a structure that is populated which contains members called initialize(), yield(), disconnect() where the structure could be populated with iotf_initialize(&myStruct).

(The above are only suggestions).

**Comment by amitmangalvedkar** [comment]
@nkolban 
Thanks a lot for your valuable suggestion. We definitely look forward for your comments and suggestions, which help us in refining the client libraries.   
Considering your suggestions of appending iotf_ (or for that matter watson_iot_) to the functions, our goal is to maintain the as close function name (or method names) and class names (wherever applicable), as possible, across all the languages - be it Embedded C, Java, Python, Node.js or C#.   
Also the libraries have been existing for quite sometime and many users have developed their applications using the existing names. Changing these names would break down their flows.  
Nevertheless we understand your concern as this case is slightly unique to C (wherein we do not have any namespaces). So we are discussing these changes and if its decided to change the names we would go through it. 

Thanks and Regards
Amit M Mangalvedkar

**Comment by Lokesh-K-Haralakatta** [comment]
There is lot of redesign happened to this client library while adding support to SSL/TLS and Client Side Certificates for version 1.0. Even though, we still retained the same function names to maintain uniformity with our other client libraries, this library has become more robust and matured with these features. Please have a look.
