### ISSUE TITLE
free called before pointers to allocated memory are handed to callback function

### ISSUE THREAD

**Issue by kjwenger** [ibm-watson-iot/iot-embeddedc#10]
try changing the order to avoid crashes:

void messageArrived(MessageData* md)
{
	if(cb != 0) {
		MQTTMessage* message = md->message;

		char *topic = malloc(md->topicName->lenstring.len+1);

		sprintf(topic,"%.*s",md->topicName->lenstring.len,md->topicName->lenstring.data);

		void *payload = message->payload;
		((char*)payload)[message->payloadlen] = '\0';

		strtok(topic, "/");
		strtok(NULL, "/");

		char *commandName = strtok(NULL, "/");
		strtok(NULL, "/");
		char *format = strtok(NULL, "/");

		(*cb)(commandName, format, payload);
// here it comes:
		free(topic);
	}
}

**Comment by phariprasadreddy** [comment]
Thanks for reviewing the code. Added this change to the code. Thanks.
