### ISSUE TITLE
Change path in samples/Makefile

### ISSUE THREAD

**Issue by RamPrasadRP** [ibm-watson-iot/iot-embeddedc#17]
In samples/Makefile, to build ***sampleDevice***, ***helloWorld*** change the path of file iotfclient.c from  "./../iotfclient.c" to "**./../src/iotfclient.c**".
Also, for *sampleGateway* it is given as "./../gatewayclient.c" which should be "**./../src/gatewayclient.c**".

**Comment by phariprasadreddy** [comment]
Thanks for reviewing the code. Issue is fixed and merged.

**Comment by ssudhe** [comment]
After building the samples, when i run the below, i do not see any output.
can you please help me know what is missing?
linaro@linaro-gnome:~/test/iot-embeddedc/samples$ ./helloWorld 123456789123
