### ISSUE TITLE
Can't subscribe to news

### ISSUE THREAD

**Issue by xuchhao** [ibm-watson-iot/iot-embeddedc#19]
I hint according to the document content connect to the server and found that can only be publish to the server, can't subscribe to news, the callback function without printing, found that using caught tool does not subscribe to news, this problem bothering me for several days, I don't know how to solve?

**Comment by phariprasadreddy** [comment]
I have a query regarding your question. Couldn't get what exactly subscribe to news in this context. 

In this library by default it is subscribed to all the commands. You can refer code in iotfclient.c in connectiotf(Iotfclient *client) function from line no: 153-156:
if(!client->isQuickstart) {
		//Subscibe to all commands
		subscribeCommands(client);
	}
Subscribing and receiving commands you can check by running the sample samples/sampleDevice.c .

**Comment by xuchhao** [comment]
Hello, the function of the position I have add print, the return value is zero, subscribe to the success.Use caught tools, subscribe message is also sent to the server, but when I publish a message, do not subscribe to data

**Comment by xuchhao** [comment]
@phariprasadreddy,This problem I is still not solved, my program is running on PC, just to verify bluemix iot connection process, the program itself should be no problem, I doubt is the process of registered plant is wrong, can you give a test by your side device information to me?

**Comment by phariprasadreddy** [comment]
@xuchhao As per your comments I am understanding that you are able to publish events from the device to the Platform but you are not able to receive commands from the platform to the device. For receiving commands on the device there should be some application which can send commands to the device through the platform. You need to build an application to send commands to the platform. 
You can build an application for sending commands using node-red. 
You can refer the section **7. Send commands to your device** in the link below.
[](https://developer.ibm.com/recipes/tutorials/getting-started-with-watson-iot-platform-using-node-red/)

Please let us know if you need any help

**Comment by Lokesh-K-Haralakatta** [comment]
No further reply. Hence closing this issue.
