### ISSUE TITLE
Any plan to support SSL/TLS connection in the embbeded C client?

### ISSUE THREAD

**Issue by massimilianozilio** [ibm-watson-iot/iot-embeddedc#22]
Hi, 
I am working on an home gateway project based on embedded linux and I require the connection between the GW and watson to be secure and encrypted. Given that IBM-watson platform supports TLS connection,  I was a little bit surprised to see the following comment in the iot-embedded C code:
    //TODO : change to 8883 if registered, add support when available in MQTTClient

Is any plan to support SSL/TLS connection in the embedded C client  and if yes, when do you think it will be available?

I believe the client provided under this project https://github.com/ibm-messaging/iot-raspberrypi does support TLS connection but the project hasn't been updated for a long time. Is it a project that IBM is going to maintain going forward?  

I am basically trying to understand which C client is going to be officially recommended one for users who requires SSL/TLS support.

Thanks,
Massimiliano

**Comment by nkolban** [comment]
Howdy Massimiliano, I had a similar puzzle and looked into it some.  This project is based on the Eclipse Paho MQTT client ... see https://github.com/eclipse/paho.mqtt.embedded-c.  If we look at THAT project, we find that it does not appear to support TLS/SSL ... however ... all is not lost.  If we look in that project we find that the networking layer has been separated from the MQTT functions.  Specifically, look at https://github.com/eclipse/paho.mqtt.embedded-c/blob/master/MQTTClient-C/src/linux/MQTTLinux.c

There we find the networking functions that the MQTT client hopes to find available.  These include a network initialization, a network write and a network read.  In a test, I replaced these calls with the utilization of an open source SSL library ... and it all "just worked".  I was able to send MQTT calls over TLS without incident.  This makes me feel that leveraging this library (IBM IoT Platform) should be able to transparently leverage an SSL enabled MQTT client.

**Comment by jeffdare** [comment]
Hi @massimilianozilio @nkolban ,

Yes, Indeed this library is written in a way for the user to import his own implementation of Networking layer. The current library has support for linux OS with the MQTTLinux.c as @nkolban pointed out. 

Thanks @nkolban for your proactive inputs for this. We encourage community developers for all our libraries. Can you contribute your implementation with SSL library to this repository, as it can help others. 

Thanks!!
Jeff

**Comment by Lokesh-K-Haralakatta** [comment]
SSL/TLS Support and Client Side Certificates based authentication added as part of release 1.0

**Comment by PravallikaKG** [comment]
Hi Lokesh, Please provide the link for release 1.0, which has the TLS support in Paho Embedded C Client.
