### ISSUE TITLE
publish sensor data in json

### ISSUE THREAD

**Issue by ssudhe** [ibm-watson-iot/iot-embeddedc#24]
I have connected an i2c sensor (accelorometer) to a board running linux. The sensor reg values need to published 
Say the values are in unsigned char regval, how to i put in a json format required for the below call.
How should the payload be?
rc= publishEvent(&client, "status","json", "{\"d\" : {\"temp\" : 34 }}", QOS0);

Thanks,
Shubha

**Comment by Lokesh-K-Haralakatta** [comment]
Please have a look at our sample with the library - https://github.com/ibm-watson-iot/iot-embeddedc/blob/master/samples/sampleDevice.c. If you have values stored in variables, then you need to build the payload using sprintf.
