### ISSUE TITLE
domain input parameter in iotfclient's Initialize  function.

### ISSUE THREAD

**Issue by sureshmanchi** [ibm-watson-iot/iot-embeddedc#25]
iotfclient's Initialize function takes domain as input parameter
`int initialize(Iotfclient *client, char *orgId, char *domain, char *deviceType, char *deviceId, char *authmethod, char *authtoken);`

What should be the value for domain? Seems the documentation is not updated. Please fix.

**Comment by Lokesh-K-Haralakatta** [comment]
The latest github documentation updated as part of version 1.0. Please refer.
