### ISSUE TITLE
Connecting Registered device to ibm-watson-iot not working

### ISSUE THREAD

**Issue by sunithachinnam** [ibm-watson-iot/iot-embeddedc#26]
updated ./device.cfg file and trying to connect to ibm-watson-iot app on 8883 port which support secure connection, but it is unable to connect. do i need to add TLS support in MQTT? as i see the comment   //TODO : change to 8883 if registered, add support when available in MQTTClient

**Comment by sathipal** [comment]
The secure connection is not supported as of now. You can follow the discussion here https://github.com/ibm-watson-iot/iot-embeddedc/issues/22 to see how you can create a secure connection using this library.

**Comment by Lokesh-K-Haralakatta** [comment]
SSL/TLS Support and Client Side Certificates based authentication added as part of release 1.0
