### ISSUE TITLE
How to define the IOT_EMBDC_HOME variable?

### ISSUE THREAD

**Issue by mmdsantos** [ibm-watson-iot/iot-embeddedc#28]
Hello all,

I am using a Linux system to cross compile the code, passing it to an embedded system. I copied the **_helloWorld_** executable, as well as the shared library **_libiotfdeviceclient.so_** to my system. When I try to run the executable, I get the following error:
```
 Connection returned rc = -15872.
 Quitting..
```
When I tried to run the same executable compiled to my computer I had the same problem. After defining the IOT_EMBDC_HOME system variable, I can run it successfully in my computer.

My question is where to define this variable in the system running the code, when it is not the same system where the code was compiled.

Thank you

**Comment by Lokesh-K-Haralakatta** [comment]
Hi,

You can define IOT_EMBDC_HOME as one of the environment variable either System wide or session wide. Looking at your error message, I don't think it's due to IOT_EMBDC_HOME, looks like the cross compiled code is not working properly on the machine where you are trying to run the sample.

**Comment by mmdsantos** [comment]
@Lokesh-K-Haralakatta, thank you for your answer. 

I got exactly the same error when running the executable from my computer before defining the IOT_EMBDC_HOME variable. Only after defining it I can run the executable, so I am pretty sure that it has influence. You can see it here:

```
miguel@ms-VB:~/Desktop/IBM/iot-embeddedc/build/samples$ export | grep HOME
declare -x HOME="/home/miguel"
miguel@ms-VB:~/Desktop/IBM/iot-embeddedc/build/samples$ ./helloWorld orgID devType devID token 0
Connection returned rc = -15872.
 Quitting..
miguel@ms-VB:~/Desktop/IBM/iot-embeddedc/build/samples$ export IOT_EMBDC_HOME=$HOME/Desktop/IBM/iot-embeddedc/
miguel@ms-VB:~/Desktop/IBM/iot-embeddedc/build/samples$ export | grep HOME
declare -x HOME="/home/miguel"
declare -x IOT_EMBDC_HOME="/home/miguel/Desktop/IBM/iot-embeddedc/"
miguel@ms-VB:~/Desktop/IBM/iot-embeddedc/build/samples$ ./helloWorld orgID devType devID token 0
Device Client Connected to orgID.messaging.internetofthings.ibmcloud.com in registered mode using Secure Connection
Connection Successful. Press Ctrl+C to quit
Publishing the event stat with rc  0
Publishing the event stat with rc  0
```
Anyway, it is still not clear what to assign to this variable in the system running the sample, if this system wasn't use in the compilation.

**Comment by Lokesh-K-Haralakatta** [comment]
Hi,
Actually the code uses the value assigned to IOT_EMBDC_HOME to derive the sample configuration file for the  sample. In your case, you can have directory with the name **_samples_** within that the required configuration file and then assign the path to parent of samples as value for IOT_EMBDC_HOME variable.

**Comment by mmdsantos** [comment]
@Lokesh-K-Haralakatta, thank you for your answer.

Following your suggestion, I assigned the value "**/root/ibm/**" to the variable **IOT_EMBDC_HOME** in my embedded system. Then, I created a directory "**samples**" inside the **IOT_EMBDC_HOME** directory, and I moved the file "**device.cfg**" to the "**samples**" directory.

I'm getting the same error as before. Is there any other file I need to move, or any other directory I need to create inside my system? 

Thank you

**Comment by mmdsantos** [comment]
@Lokesh-K-Haralakatta 

Ok, I solved the problem. It is necessary to copy the file **IoTFoundation.pem** to the **IOT_EMBDC_HOME** directory. This way I can connect to the platform. The samples directory makes no difference in this case

**Comment by Lokesh-K-Haralakatta** [comment]
Yes, you need IoTFOundation.pem file for secure connection to the platform. Even samples directory is also required if you are using other samples like sampleDevice and sampleGateway, for helloWorld sample it's not required as it does not use any configuration file.
