### ISSUE TITLE
Issue with the callback handler

### ISSUE THREAD

**Issue by mmdsantos** [ibm-watson-iot/iot-embeddedc#29]
Hello,

I was doing some tests using the C SDK and I'm having a problem. I'm trying to implement a callback handler but this handler doesn't receive the payload size, neither inserts a string terminator in the end of the payload.

If I send 2 consecutive commands and the payload of the first is bigger than the payload of second, it will have the "remains" of the first payload.

Example:
1st Command Sent: "**hello world!**"
2nd Command sent: "**hi!!**"

Output on my device:
1st -
```
------------------------------------
The command received :: my-cmd
format : text
Payload is : hello world!
------------------------------------
```
2nd -
```
------------------------------------
The command received :: my-cmd
format : text
Payload is : hi!!o world!
------------------------------------
```

The SDK functions should handle the memory allocation better and insert a string terminator in the end of the payload, or at least have a way to pass the length of the payload as argument to the callback handler so I can put it myself.

Am I missing something? How can I avoid this?

Thank you

**Comment by Lokesh-K-Haralakatta** [comment]
Hi,
The piece of code that you are reporting is  part of user application it's nothing to do with Client library code. The output you are seeing is from sample application - deviceSample.c present under samples directory. You can update myCallback function in the deviceSample.c according to your requirement, build and execute the code.

Thx,
Loki...

**Comment by mmdsantos** [comment]
@Lokesh-K-Haralakatta I can't update the myCallback function in the sampleDevice.c if the payload length isn't passed to this function. 

The function messageArrived in the deviceclient.c code only passes the commandName, format and payload (line 122).  Comparing with the function gatewayMessageArrived on the gatewayclient.c code, the parameters passed are type, id, commandName, format, payload AND **payloadlen**. (line 252)

My question is, if how can I parse correctly the payload if the only argument my Command Handler function receives is a pointer to the payload, without the length of the payload?
