### ISSUE TITLE
Paho Embedded-C ?

### ISSUE THREAD

**Issue by chainhead** [ibm-watson-iot/iot-embeddedc#33]
How is this project different from [Paho MQTT Embedded-C](https://github.com/eclipse/paho.mqtt.embedded-c) ?

**Comment by icraggs** [comment]
This is a library to make is easier to interact with the IBM Watson IoT Platform, IBM's cloud IoT service.   It uses the Paho library for MQTT support.

https://internetofthings.ibmcloud.com/
https://www.ibm.com/internet-of-things
