### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by AlexShkunov** [ibm-watson-iot/iot-embeddedc#6]
devicemanagementclient.c has arguments for deviceActions and Firmware actions, but ignores passed values and uses Hardcoded ones instead.

void publishManageEvent(ManagedDevice *client, long lifetime, int supportFirmwareActions,
	int supportDeviceActions, char* reqId)

sprintf(payload,strPayload,client->DeviceData.metadata.metadata,lifetime,**"true","true"**,client->DeviceData.deviceInfo.serialNumber,client->DeviceData.deviceInfo.manufacturer, client->DeviceData.deviceInfo.model,client->DeviceData.deviceInfo.deviceClass,client->DeviceData.deviceInfo.description,client->DeviceData.deviceInfo.fwVersion,client->DeviceData.deviceInfo.hwVersion,client->DeviceData.deviceInfo.descriptiveLocation,uuid_str);

**Comment by phariprasadreddy** [comment]
@AlexShkunov 
Code is updated with these changes. You can expect it in the next update.

**Comment by phariprasadreddy** [comment]
@AlexShkunov
Updated code is now available.
