### ISSUE TITLE
SubscribeCommands_dm hardcoded reference

### ISSUE THREAD

**Issue by AlexShkunov** [ibm-watson-iot/iot-embeddedc#7]
Function takes as an argument ManagedDevice structure but never uses it and operates on top of hardcoded reference to deviceClient.c

int subscribeCommands_dm(**ManagedDevice *client**)
{
	int rc = -1;

	rc = subscribeCommands(**&deviceClient**);
	if(rc >=0){
		**Client *c;
		c= &(deviceClient.c);**
		rc = MQTTSubscribe(c, "iotdm-1/response", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/observe", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/cancel", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/mgmt/initiate/device/reboot", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/mgmt/initiate/device/factory_reset", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/mgmt/initiate/firmware/download", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/mgmt/initiate/firmware/update", QOS0, messageCame);
		rc = MQTTSubscribe(c, "iotdm-1/device/update", QOS0, messageCame);
	}else{
		printf("iotf subscribe faild ");
	}
	return rc;
}

**Comment by phariprasadreddy** [comment]
@AlexShkunov 
Code is updated with these changes. You can expect it in the next update.

**Comment by phariprasadreddy** [comment]
@AlexShkunov
Updated code is now available.
