### ISSUE TITLE
callback for Reboot is not triggered

### ISSUE THREAD

**Issue by AlexShkunov** [ibm-watson-iot/iot-embeddedc#8]
There is set callback handler setManagedHandler_dm(&client, managedCallBack);

Callback is received for Manage action, but Reboot message doesn't reach the Client, Thus making it impossible to trigger an action from the Platform.

![managecallback](https://cloud.githubusercontent.com/assets/5401888/14708237/2c1a83ce-07d2-11e6-8c16-641f3ff89e44.png)
![rebootsub](https://cloud.githubusercontent.com/assets/5401888/14708254/43ae5dc6-07d2-11e6-9100-883f3ca30468.png)

**Comment by phariprasadreddy** [comment]
@AlexShkunov 
The current version doesn't have support for Device actions (Reboot, Factory reset, Firmware Download and Firmware update). We are currently working on them. You can expect these features in the next update.

**Comment by phariprasadreddy** [comment]
@AlexShkunov
Updated code is now available.
